---


- name: setup repo for all servers
  hosts: all
  become: yes
  roles:
    - common 

- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - lbtier

- name: setup application tier
  hosts: apps
  become: yes
  roles:
    - apptier

- name: setup db tier
  hosts: appdbs
  become: yes
  roles:
    - dbtier

---
