---

- name: install progress
  yum:
    name: postgresql-server
    state: latest

- name: enable apache at boot
  service:
    name: postgresgl
    enabled: yes

- name: tell user to finish setting up postgres
  debug:
    msg: "Either uncomment the postgres setup or manually login and initialize"

- name: initilize postgres
  command: postgresql-setup initdb

- name: initilize postgres some more
  command: chkconfig postgresql on

- name: start postgres
  service:
    name: postgresql.service
    state: started

---
